name: ismart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  geolocator: ^10.1.0
  flutter_svg: ^2.0.9
  permission_handler: ^11.2.1
  logging: ^1.1.0
  intl: ^0.18.0
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  flutter_secure_storage: ^6.0.0
    #network
  connectivity_plus: ^3.0.2
  dio: ^4.0.6
  simple_animations: ^5.0.2

    #maps
  google_maps_flutter: ^2.5.3
  flutter_polyline_points: ^2.0.0
  google_maps_cluster_manager: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
